db_password_name                  = "DatabasePassword"
db_password_value                 = "Password@123"
environment                       = "dev"
resource_group_name               = "rg-tfstate"
location                          = "Central India"
postgresql_administrator_login    = "dbadmin"
postgresql_administrator_password = "Password@123"